# Generated by Django 4.1.7 on 2023-03-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='hours',
            field=models.PositiveSmallIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='title',
            field=models.CharField(max_length=5),
        ),
    ]
