# Generated by Django 4.1.7 on 2023-03-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_alter_coursemodel_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodel',
            old_name='title',
            new_name='name',
        ),
    ]
